// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP_2ksqVxSbQM4XaStG4DBlmBwqZal11g',
    appId: '1:600571265229:web:38e43edc69720c61ade984',
    messagingSenderId: '600571265229',
    projectId: 'denv-flutter-trainning',
    authDomain: 'denv-flutter-trainning.firebaseapp.com',
    databaseURL: 'https://denv-flutter-trainning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'denv-flutter-trainning.appspot.com',
    measurementId: 'G-3Q1X631BF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOs495-6rq-ScYu25nU-Y1mHiA793OdS0',
    appId: '1:600571265229:android:5eeb9507a9b3ad81ade984',
    messagingSenderId: '600571265229',
    projectId: 'denv-flutter-trainning',
    databaseURL: 'https://denv-flutter-trainning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'denv-flutter-trainning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqSziKB1eMWfQ4MSf4c5m0sHgvkcF2nOs',
    appId: '1:600571265229:ios:81dcf9b0cbea4b36ade984',
    messagingSenderId: '600571265229',
    projectId: 'denv-flutter-trainning',
    databaseURL: 'https://denv-flutter-trainning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'denv-flutter-trainning.appspot.com',
    iosBundleId: 'com.example.denvFlutterCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqSziKB1eMWfQ4MSf4c5m0sHgvkcF2nOs',
    appId: '1:600571265229:ios:1e92488ce49755a3ade984',
    messagingSenderId: '600571265229',
    projectId: 'denv-flutter-trainning',
    databaseURL: 'https://denv-flutter-trainning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'denv-flutter-trainning.appspot.com',
    iosBundleId: 'com.example.denvFlutterCleanArchitecture.RunnerTests',
  );
}
